console.log('🔍 VERIFICACIÓN DE VARIABLES EN RAILWAY');
console.log('=====================================');
console.log('');
console.log('📋 VARIABLES NECESARIAS PARA EL BOT:');
console.log('');
console.log('✅ DISCORD_TOKEN (Discord bot token)');
console.log('   - Ya configurado ✅');
console.log('');
console.log('📱 PARA VERIFICAR EN RAILWAY:');
console.log('');
console.log('1. Ve a: https://railway.app/project/striking-transformation');
console.log('2. Busca sección "Variables" o "Environment Variables"');
console.log('3. Verifica que tengas:');
console.log('   • DISCORD_TOKEN = tu_token_aqui');
console.log('   • NODE_ENV = production (opcional pero recomendado)');
console.log('   • PORT = 3000 (Railway asigna automáticamente)');
console.log('');
console.log('⚠️ SI FALTA DISCORD_TOKEN:');
console.log('   - El bot no podrá conectarse a Discord');
console.log('   - Aparecerá error de autenticación');
console.log('');
console.log('📤 ENVÍA SCREENSHOT DE:');
console.log('   • La sección Variables en Railway');
console.log('   • El resultado del nuevo deploy');